import type { Metadata } from "next";
import {
  Bebas_Neue as BebasNeue,
  Inter,
  Open_Sans as OpenSans,
  Poppins,
  Raleway,
  Roboto,
} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const poppins = Poppins({ subsets: ["latin"], weight: "400" });
export const raleway = Raleway({ subsets: ["latin"], weight: "400" });
export const roboto = Roboto({ subsets: ["latin"], weight: "400" });
export const bebasNeue = BebasNeue({ subsets: ["latin"], weight: "400" });
export const openSans = OpenSans({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
